%%
%% IEEEtai.cls 2020/07/27 version V1.0
%%
%% IEEE Transaction on Artificial Intelligence document class file for LaTeX2e
%%
%% Copyright (C) IEEE Transaction on Artificial Intelligence 
%% for LaTeX version 1.0, by Aptara, India
%% 
%% IEEEtai.cls is based on IEEEtran.cls version V1.7a.
%%

\ProvidesClass{IEEEtai}[2020/07/27 V1.0 by Aptara]
\NeedsTeXFormat{LaTeX2e}

\LoadClass[journal]{IEEEtran}

\endinput
